#!/bin/bash

convert () {
    ods="$1"
    # echo "$ods"
    json="json/$(basename "$ods" .ods).json"
    # echo $json
    if [ ! -f "$json" ] || [ "$ods" -nt "$json" ]; then
    # if [ "$ods" -nt "$json" ]; then
        # echo "newer"
        target/debug/ods_to_json "$ods"
    fi
}

if [ $# -eq 0 ]; then
    for ods in ods/*.ods; do
        convert $ods
    done

    # ./clean
else
    ods="$1"
    if [ -f "$ods" ]; then
        convert "$ods"
    # else
    #     echo "$ods doesn't exist"
    #     json="json/$(basename "$ods" .ods).json"
    #     if [ -f "$json" ]; then
    #         echo "removing $json"
    #         rm "$json"
    #     fi
    fi
fi
